[package]
name = "heihacheem-bot"
version = "0.1.0"
authors = ["david ğŸ• <david.wallin.lewis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
tokio = { version = "1.5", features = ["full"] }
serde = "1"
serde_json = "1"
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8"
nom = "6"
